Feature: Setup of Object Reposistory- Non functional

  @RegsitrationWithPAN
  Scenario: Initialize Object Repository
    Given Following Elements Exists
      | Label                                             | Locator                                                                                                                                                      |
      | CheckSetup.SMELink                                | //*[@id="main"]/div[2]/header/div/div/div/div/div[2]/div/div[3]/div/div/div/div/div[1]/div[2]/ul[1]/li[3]/a                                                  |
      | CheckSetup.WelcomeText                            | //*[@id="main"]/div[2]/div[1]/div/div/div/div[1]/div/div[3]/div/div/div/div/div[1]                                                                           |
      | AutheticationPage.advertismentBanner              | //*[@id='pr_id_1']                                                                                                                                           |
      | AutheticationPage.readMoreLink                    | /html/body/app-root/app-landing-page/section/div/div/div[1]/app-tab-details/div/p-tabview/div/div/div[1]/a                                                   |
      | AutheticationPage.mobileNumberInput               | //*[@id="mobileNumber"]                                                                                                                                      |
      | AcceptCookieFrameId                               | destination_publishing_iframe_hdfcbank_0                                                                                                                     |
      | OkcookieBtn                                       | //*[@id="onetrust-accept-btn-handler"]                                                                                                                       |
      | AutheticationPage.getOTPButton                    | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-mobile-number-verification/form/section/div[2]/button                                        |
      | AutheticationPage.termCondLink                    | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-mobile-number-verification/form/section/div[2]/div[2]/p/a[1]                                 |
      | AutheticationPage.privacyPolicyLink               | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-mobile-number-verification/form/section/div[2]/div[2]/p/a[2]                                 |
      | AutheticationPage.mobileNumberPrefix              | //button[@name="CD_COUNTRY_CODE"]                                                                                                                            |
      | AutheticationPage.TCAndPPMsg                      | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-mobile-number-verification/form/section/div[2]/div[2]/p                                      |
      | AutheticationPage.moreAdv                         | //*[@id='advdetails']                                                                                                                                        |
      | AutheticationPage.errorMessage                    | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-mobile-number-verification/form/section/div[2]/div[1]/rlo-ui-mobile/div/span                 |
      | AutheticationPage.TermsAndcondition               | /html/body/app-root/app-modal-component/section[1]/div/div[2]/div/div[3]/h2                                                                                  |
      | AutheticationPage.NextButton                      | /html/body/app-root/app-modal-component/section[2]/div/div/div/button                                                                                        |
      | EnterOTPPage.SentToNumber                         | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[1]/span                                                                 |
      | EnterOTPPage.ChangeNumberLink                     | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[1]/a                                                                    |
      | EnterOTPPage.otp0                                 | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[2]/ng-otp-input/div/input[1]                                            |
      | EnterOTPPage.otp1                                 | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[2]/ng-otp-input/div/input[2]                                            |
      | EnterOTPPage.otp2                                 | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[2]/ng-otp-input/div/input[3]                                            |
      | EnterOTPPage.otp3                                 | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[2]/ng-otp-input/div/input[4]                                            |
      | EnterOTPPage.otp4                                 | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[2]/ng-otp-input/div/input[5]                                            |
      | EnterOTPPage.otp5                                 | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[2]/ng-otp-input/div/input[6]                                            |
      | EnterOTPPage.ResendOTPMsg                         | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[3]/div                                                                  |
      | EnterOTPPage.ResntOTPLink                         | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/div[3]/a                                                                    |
      | EnterOTPPage.EnterOTPLabel                        | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/h1                                                                          |
      | EnterOTPPage.VerifyOTPBtn                         | /html/body/app-root/app-landing-page/section/div/div/div[2]/app-user-otp/section/button                                                                      |
      | PanRegistration.BusinessPanInput                  | //*/input[@id="taxId"]                                                                                                                                       |
      | PanRegistration.Next                              | /html/body/app-root/app-pan-verification/section/div/div[2]/div/div[6]/button[2]                                                                             |
      | PanRegistration.NameLbl                           | //*[@id="name"]                                                                                                                                              |
      | PanRegistration.Constitution                      | //*[@id="constitution"]/div/span                                                                                                                             |
      | PanRegistration.ConstitutionSelect                | //*[@id="constitution"]/div/div[1]/input                                                                                                                     |
      | PanRegistration.Pincode                           | //input[@id="pincode"]                                                                                                                                       |
      | PanRegistration.PromoCode                         | //input[@id="employeeCode"]                                                                                                                                  |
      | PanRegistration.CheckPANLink                      | /html/body/app-root/app-pan-verification/section/div/div[2]/div/div[3]/div[1]/a                                                                              |
      | PanRegistration.Header                            | /html/body/app-root/app-pan-verification/section/div/div[2]/div/div[1]/h1                                                                                    |
      | Sprint2Screen.Title                               | //*[@id="bt"]/h1                                                                                                                                             |
      | PanRegistration.ErrorLbl                          | //*[@id="taxId"]/div/span                                                                                                                                    |
      | PanRegistration.NotyouLink                        | /html/body/app-root/app-pan-verification/section/div/div[2]/div/div[3]/div[1]/a                                                                              |
      | PanRegistration.PincodeErrLabel                   | //*[@id="pincode"]/div/span                                                                                                                                  |
      | PreApprovedOffer.CongratsText                     | /html/body/app-root/app-offers-recieved/section/div/div[2]/div/div[1]/div/h1                                                                                 |
      | PreApprovedOffer.AcceptAndContinueBtn             | //*[@id="pr_id_4"]/div/div/div/div/div/div/div/div/div/p-card/div/div/div[2]/div[2]/button                                                                   |
      | PreApprovedOffer.OfferTitle                       | //*[@id="pr_id_4"]/div/div/div/div/div/div/div/div/div/p-card/div/div/div[1]                                                                                 |
      | PreApprovedOffer.HigherLoanLink                   | //*[@id="pr_id_4"]/div/div/div/div/div[1]/div/div/div/div/p-card/div/div/div[2]/div[3]/span/a                                                                |
      | AccountSelection.Header                           | /html/body/app-root/app-entity-selection/section/div/div[2]/div[1]/div/span/h6                                                                               |
      | AccountSelection.FirstAccount                     | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-user-selection/div/div[1]/div                                                         |
      | AccountSelection.SecondAccount                    | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-user-selection/div/div[2]/div                                                         |
      | AccountSelection.FirstAccountName                 | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-user-selection/div/div[1]/div/div[1]/h2                                               |
      | AccountSelection.SecondAccountName                | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-user-selection/div/div[2]/div/div[1]/h2                                               |
      | AccountSelection.NextBtn                          | /html/body/app-root/app-entity-selection/section/div/div[2]/div[3]/button[2]                                                                                 |
      | CustomerVerification.Header                       | /html/body/app-root/app-entity-selection/section/div/div[2]/div[1]/div/span/h6                                                                               |
      | CustomerVerification.CIFLbl                       | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-verification-entity/div/div[1]/div/div[2]/h3                                          |
      | CustomerVerification.AadharLbl                    | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-verification-entity/div/div[2]/div/div[2]/h3                                          |
      | CustomerVerification.AadharSelectBox              | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-verification-entity/div/div[2]/div                                                    |
      | CustomerVerification.CIFSelectBox                 | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-verification-entity/div/div[1]/div                                                    |
      | CustomerVerification.InputLabel                   | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-verification-entity/div/div[4]/h3                                                     |
      | CustomerVerification.VerificationInput            | //*[@id="FD_USER_DETAILS"]                                                                                                                                   |
      | CustomerVerification.Next                         | /html/body/app-root/app-entity-selection/section/div/div[2]/div[3]/button[2]                                                                                 |
      | CustomerVerification.ErrorMessage                 | /html/body/app-root/app-entity-selection/section/div/div[2]/div[2]/app-verification-entity/div/div[4]/div/app-text-box/div/span                              |
      | MaxAttemptPage.Header                             | /html/body/app-root/app-attempts-exceeded/section/div/div[2]/div/div[1]/div/h1                                                                               |
      | MaxAttemptPage.No                                 | /html/body/app-root/app-attempts-exceeded/section/div/div[2]/div/div[2]/div/button[1]                                                                        |
      | MaxAttemptPage.Yes                                | /html/body/app-root/app-attempts-exceeded/section/div/div[2]/div/div[2]/div/button[2]                                                                        |
      | MaxAttemptPage.ContinueMsg                        | /html/body/app-root/app-attempts-exceeded/section/div/div[2]/div/div[1]/div/h6                                                                               |
      | AadharRegistration.PanOption                      | //*[@id="mat-radio-2-input"]                                                                                                                                 |
      | AadharRegistration.PANLabel                       | //*[@id="mat-radio-2"]/label/div[2]                                                                                                                          |
      | AadharRegistration.AadharLabel                    | //*[@id="mat-radio-3"]/label/div[2]                                                                                                                          |
      | AadharRegistration.InputLabel                     | /html/body/app-root/app-pan-verification/section/div/div[2]/div/div[2]/div/div[1]/h2                                                                         |
      | AadharRegistration.InputField                     | //input[@id="taxId"]                                                                                                                                         |
      | AadharRegistration.AadharOption                   | //*[@id="mat-radio-3-input"]                                                                                                                                 |
      | URCRegistration.SkipThisStep                      | /html/body/app-root/app-offers-recieved/div/app-urc-number/section[1]/div/div[2]/div/div/div[5]/a                                                            |
      | LoanDetails.Loan_Details_Title                    | //*[@id="loanDetailsTitle"]                                                                                                                                  |
      | LoanDetails.Sector_Label                          | //*[@id="sectorLabel"]                                                                                                                                       |
      | LoanDetails.Sector_Dropdown                       | //*[@id="sector"]/div                                                                                                                                        |
      | LoanDetails.Facility_Label                        | //*[@id="facilityLabel"]                                                                                                                                     |
      | LoanDetails.Facility_Dropdown                     | //*[@id="facility"]/div                                                                                                                                      |
      | LoanDetails.Add_Product_Button                    | //*[@id="loanDetailsAddProduct"]                                                                                                                             |
      | LoanDetails.Next_Button                           | //*[@id="loanDetailsNext"]                                                                                                                                   |
      | LoanDetails.TotalLoanAmount                       | /html/body/app-root/app-loan-details/section/div/div[4]/div/div/div/span                                                                                     |
      | LoanDetails.Product_Details_Title                 | /html/body/app-root/app-loan-details/div[1]/app-product-details/section/div/div[2]/div/form/div[1]/h1                                                        |
      | LoanDetails.Type_Label                            | /html/body/app-root/app-loan-details/div[1]/app-product-details/section/div/div[2]/div/form/div[2]/h2                                                        |
      | LoanDetails.Type_Dropdown                         | //*[@id="facilityCode"]/div                                                                                                                                  |
      | LoanDetails.Purpose_Label                         | /html/body/app-root/app-loan-details/div[1]/app-product-details/section/div/div[2]/div/form/div[3]/h2                                                        |
      | LoanDetails.Purpose_Textfield                     | //input[@id="loanPurpose"]                                                                                                                                   |
      | LoanDetails.Loan_Amount_Label                     | /html/body/app-root/app-loan-details/div[1]/app-product-details/section/div/div[2]/div/form/div[4]/h2[1]                                                     |
      | LoanDetails.Loan_Amount_TextField                 | //input[@id="loanAmount"]                                                                                                                                    |
      | LoanDetails.Existing_Loan_Transfer_CheckBox       | //*[@id="takeover"]/label/div                                                                                                                                |
      | LoanDetails.Add_Button                            | //*[@id="productDetailsAdd"]                                                                                                                                 |
      | LoanDetails.ProductList_Name                      | /html/body/app-root/app-loan-details/section/div/div[4]/div[1]/div/div/div[1]/span[1]                                                                        |
      | LoanDetails.ProductList_Amount                    | /html/body/app-root/app-loan-details/section/div/div[4]/div[1]/div/div/div[1]/span[2]                                                                        |
      | LoanDetails.ProductList_Edit_Button               | //*[@id="loanDetailsEditProduct"]                                                                                                                            |
      | LoanDetails.Update_Button                         | //*[@id="productDetailsUpdate"]                                                                                                                              |
      | LoanDetails.Delete_Button                         | //*[@id="productDetailsDelete"]                                                                                                                              |
      | URC.Title                                         | /html/body/app-root/app-offers-recieved/div/app-urc-number/section[1]/div/div[2]/div/div/div[2]/h1                                                           |
      | URC.NumberLabel                                   | /html/body/app-root/app-offers-recieved/div/app-urc-number/section[1]/div/div[2]/div/div/div[3]/h2                                                           |
      | URC.udyamNumber                                   | //input[@id='udyamNumber']                                                                                                                                   |
      | URC.udyamSubmit                                   | //*[@id="udyamSubmit"]                                                                                                                                       |
      | URC.donthaveurcLink                               | //*[@id="udyamGuide"]                                                                                                                                        |
      | URC.udyamCreate                                   | //*[@id="udyamCreate"]                                                                                                                                       |
      | URC.udyamPopup                                    | //*[@id="udyamPopup"]                                                                                                                                        |
      | URC.udyamChangeUrc                                | //*[@id="udyamChangeUrc"]                                                                                                                                    |
      | URC.udyamContinueWithoutOffer                     | //*[@id="udyamContinueWithoutOffer"]                                                                                                                         |
      | URC.udyamMessage                                  | //h3[@id='udyamMessage']                                                                                                                                     |
      | URC.udyamNotInterested                            | //*[@id="udyamNotInterested"]                                                                                                                                |
      | URC.udyamContinue                                 | //*[@id="udyamContinue"]                                                                                                                                     |
      | URC.udyamChange                                   | //*[@id="udyamChange"]                                                                                                                                       |
      | URC.udyamClose                                    | //*[@id="udyamClose"]                                                                                                                                        |
      | URC.notRegisteredTitle                            | //*[@id="     "]                                                                                                                                             |
      | URC.udyamNumberError                              | //*[@id="     "]                                                                                                                                             |
      | URC.seemsLikeNameMismatch                         | //h1[contains(text(),'Seems like there is a name mismatch!')]                                                                                                |
      | URC.errorMessage                                  | //*[@id="udyamNumber"]/div/span                                                                                                                              |
      | URC.NotMicroMsg                                   | //*[@id="udyamMessage"]                                                                                                                                      |
      | URC.MaxAttemptMsg                                 | /html/body/app-root/app-attempts-exceeded/section/div/div[2]/div/div[1]/div/h1                                                                               |
      | DocumentAcceptance.docAcceptenceBack              | //*[@id="docAcceptenceBack"]                                                                                                                                 |
      | DocumentAcceptance.docAcceptenceNext              | //*[@id="docAcceptenceNext"]                                                                                                                                 |
      | DocumentAcceptance.docAcceptenceTitle             | //*[@id="docAcceptenceTitle"]                                                                                                                                |
      | DocumentAcceptance.docAcceptenceNetbanking        | //*[@id="docAcceptenceNetbanking"]                                                                                                                           |
      | DocumentAcceptance.docAcceptenceEsign             | //*[@id="docAcceptenceEsign"]                                                                                                                                |
      | DocumentAcceptance.docAcceptenceSubmittedTitle    | //*[@id="docAcceptenceSubmittedTitle"]                                                                                                                       |
      | DocumentAcceptance.docAcceptenceClose             | //*[@id="docAcceptenceClose"]                                                                                                                                |
      | ApplicantDetails.next                             | //*[@id="     "]                                                                                                                                             |
      | Applicant.Partner.entityName                      | //*[@id="     "]                                                                                                                                             |
      | Applicant.Partner.aPAN                            | //*[@id="     "]                                                                                                                                             |
      | Applicant.Partner.aDOB                            | //*[@id="     "]                                                                                                                                             |
      | Applicant.Partner.aAddress                        | //*[@id="     "]                                                                                                                                             |
      | Applicant.Partner.edit                            | /html/body/app-root/app-applicant-details/section/div/div[2]/app-applicant-type/div[1]/div[2]/div/div/div/div[2]/div[4]/div/a                                |
      | Applicant.Partner.next                            | /html/body/app-root/app-applicant-details/section/div/div[2]/div[2]/button[2]                                                                                |
      | Applicant.Director.entityName                     | //*[@id="     "]                                                                                                                                             |
      | Applicant.Director.aPAN                           | //*[@id="     "]                                                                                                                                             |
      | Applicant.Director.aDOB                           | //*[@id="     "]                                                                                                                                             |
      | Applicant.Director.aAddress                       | //*[@id="     "]                                                                                                                                             |
      | Applicant.Director.editIcon                       | //*[@id="     "]                                                                                                                                             |
      | Applicant.Director.Co-applicant                   | //*[@id="     "]                                                                                                                                             |
      | Applicant.addCo-applicant                         | //button[contains(text(),'+ Add co-applicant')]                                                                                                              |
      | Applicant.Co-applicant.pan                        | //input[@id='taxId']                                                                                                                                         |
      | Applicant.Co-applicant.firstName                  | //input[@id='firstName']                                                                                                                                     |
      | Applicant.Co-applicant.middleName                 | //input[@id='middleName']                                                                                                                                    |
      | Applicant.Co-applicant.lastName                   | //input[@id='lastName']                                                                                                                                      |
      | Applicant.Co-applicant.dob                        | //body/app-root[1]/app-applicant-details[1]/div[1]/app-edit-applicant[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[6]/p-calendar[1]/span[1]/input[1] |
      | Applicant.Co-applicant.address                    | //input[@id='addressLine1']                                                                                                                                  |
      | Applicant.Co-applicant.pincode                    | //input[@id='pincode']                                                                                                                                       |
      | Applicant.Co-applicant.customerId                 | //input[@id='customerId']                                                                                                                                    |
      | Applicant.Co-applicant.addbutton                  | //body/app-root[1]/app-applicant-details[1]/div[1]/app-edit-applicant[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[10]/button[1]                     |
      | Applicant.applicantDetailsTitle                   | //h2[contains(text(),'Applicant Details')]                                                                                                                   |
      | Applicant.Co-applicant.editIcon                   | //body/app-root[1]/app-applicant-details[1]/section[1]/div[1]/div[2]/app-applicant-type[1]/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]/img[1]                    |
      | Applicant.Co-applicant.companyPan                 | //input[@id="taxId"]                                                                                                                                         |
      | Applicant.Co-applicant.businessName               | //input[@id='businessName']                                                                                                                                  |
      | Applicant.Co-applicant.email                      | //*[@id="     "]                                                                                                                                             |
      | Applicant.Co-applicant.industry                   | //*[@id="     "]                                                                                                                                             |
      | Applicant.Co-applicant.sub_Industry               | //*[@id="     "]                                                                                                                                             |
      | Applicant.Co-applicant.Date_Of_Incorporation      | //body/app-root[1]/app-applicant-details[1]/div[1]/app-edit-applicant[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[8]/p-calendar[1]/span[1]/input[1] |
      | Applicant.Co-applicant.pin_Code                   | //input[@id="pincode"]                                                                                                                                       |
      | Applicant.Co-applicant.update                     | //button[contains(text(),'Update')]                                                                                                                          |
      | Applicant.Co-applicant.updatedDetails             | //body/app-root[1]/app-applicant-details[1]/section[1]/div[1]/div[2]/app-applicant-type[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]                         |
      | EntityScreen.addressType                          | //*[@id="addressType"]/div/span                                                                                                                              |
      | EntityScreen.addressLine1                         | //input[@id='addressLine1']                                                                                                                                  |
      | EntityScreen.addressFetchCommunicationAddress     | /html/body/app-root/app-entity-details/section/div/div[3]/app-address-list/section/div/div[2]/div/div[3]/div[2]/div/div/h3                                   |
      | EntityScreen.addressTypeLabel                     | //h2[@id='addressTypeLabel']                                                                                                                                 |
      | EntityScreen.addressLabel                         | //*[@id="addressLabel"]                                                                                                                                      |
      | EntityScreen.pincodeLabel                         | //*[@id="pincodeLabel"]                                                                                                                                      |
      | EntityScreen.pincode                              | //input[@id='pincode']                                                                                                                                       |
      | EntityScreen.name                                 | //*[@id="name"]                                                                                                                                              |
      | EntityScreen.email                                | //input[@id="email"]                                                                                                                                         |
      | EntityScreen.gender                               | //*[@id="gender"]                                                                                                                                            |
      | EntityScreen.dob                                  | //*[@id="dob"]                                                                                                                                               |
      | EntityScreen.companyName                          | //*[@id="companyName"]                                                                                                                                       |
      | EntityScreen.date_Of_Incorporation                | //input[@id="icon"]                                                                                                                                          |
      | EntityScreen.industry                             | //*[@id="industry"]/div/span                                                                                                                                 |
      | EntityScreen.subIndustry                          | //body/app-root[1]/app-entity-details[1]/section[1]/div[1]/div[2]/div[1]/div[2]/div[5]/p-dropdown[1]/div[1]/span[1]                                          |
      | EntityScreen.entityDetailsTitle                   | //h2[@id='entityDetailsTitle']                                                                                                                               |
      | EntityScreen.businessNameLabel                    | //*[@id="businessNameLabel"]                                                                                                                                 |
      | EntityScreen.businessName                         | //input[@id='businessName']                                                                                                                                  |
      | EntityScreen.emailLabel                           | //*[@id="emailLabel"]                                                                                                                                        |
      | EntityScreen.industryLabel                        | //*[@id="industryLabel"]                                                                                                                                     |
      | EntityScreen.subIndustryLabel                     | //*[@id="subIndustryLabel"]                                                                                                                                  |
      | EntityScreen.dateOfIncorporationLabel             | //input[@id='icon']                                                                                                                                          |
      | EntityScreen.entityDetailsAddCommunicationAddress | //button[@id='entityDetailsAddCommunicationAddress']                                                                                                         |
      | EntityScreen.entityDetailsBack                    | //*[@id="entityDetailsBack"]                                                                                                                                 |
      | EntityScreen.entityDetailsNext                    | //button[@id='entityDetailsNext']                                                                                                                            |
      | EntityScreen.entityDetailsAddNew                  | //button[@id='entityDetailsAddNew']                                                                                                                          |
      | EntityScreen.entityDetailsChange                  | //a[@id='entityDetailsChange']                                                                                                                               |
      | EntityScreen.addressDetailsAdd                    | //button[@id='addressDetailsAdd']                                                                                                                            |
      | EntityScreen.addressDetailsDelete                 | //button[@id='addressDetailsDelete']                                                                                                                         |
      | EntityScreen.addressDetailsUpdate                 | //button[@id='addressDetailsUpdate']                                                                                                                         |
      | EntityScreen.addressListClose                     | //*[@id="addressListClose"]                                                                                                                                  |
      | EntityScreen.addressDetailsClose                  | //*[@id="addressDetailsClose"]                                                                                                                               |
      | EntityScreen.selectedAddress                      | //body/app-root[1]/app-entity-details[1]/section[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]                                                         |
      | EntityScreen.addressDetailsEdit                   | //                                                                                                                                                           |
      | EntityScreen.addedCommunicationAddressEditIcon    | //body/app-root[1]/app-entity-details[1]/section[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/img[1]                                           |
      | EntityScreen.addedCommunicationAddress            | //body/app-root[1]/app-entity-details[1]/section[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]                                                         |
      | EntityScreen.updatedCommunicationAddress          | //body/app-root[1]/app-entity-details[1]/section[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]                                                         |
